#""" SAMOS CRAWLER CONFIGURATION FILE """#
# NO TRAILING SLASHES!

samos :
- proj_directory: /r/coaps/ftp/samos_pub/data

- categories:
  # datasets
  - quick:
    - directory: quick
    - description:
    - table_name: samos_quick

  - intermediate:
    - directory: intermediate
    - description:
    - table_name: samos_intermediate

  - research:
    - directory: research
    - description:
    - table_name: samos_research

- nomenclature:
  # file details
  - extension: nc
  - handler: script
  - action:

  # file naming pattern
  - filename:
    - vessel_id:
      - type: VARCHAR
    - date:
      - type: DATE
    - v:
      - type: INT

  # file data
  # should return from action as key => value
  # where variable_name is key
  - data:
    - time:
        - variable_name: time
        - units: minutes since 1-1-1980 00:00 UTC
        - min_val: 0
        - max_val: 21565439
        - type: BIGINT
    - latitude:
        - variable_name: lat
        - units: degrees (+N)
        - min_val: -90
        - max_val: 90
        - type: FLOAT
    - longitude:
        - variable_name: lon
        - units: degrees (+E)
        - min_val: 0
        - max_val: 360
        - type: FLOAT
    - calendar_date:
        - variable_name: date
        - units: YYYYMMDD UTC
        - min_val:
        - max_val:
        - type: DATE
    - time_of_day:
        - variable_name: time_of_day
        - units: hhmmss UTC
        - min_val: 0
        - max_val: 2359
        - type: BIGINT
